auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 0
  http_server_idle_timeout: 5m
  http_server_write_timeout: 10m
  http_server_read_timeout: 10m

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  chunk_target_size: 1572864
  max_chunk_age: 1h
#  max_transfer_retries: 0 
  wal:
    dir: "/tmp/wal"

schema_config:
  configs:
  - from: 2020-05-15
    store: boltdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 744h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

querier:
#  query_timeout: 10m0s
  tail_max_duration: 1h0m0s
  engine:
#    timeout: 10m0s
    max_look_back_period: 30s
  max_concurrent: 100
  query_store_only: false

limits_config:
#  enforce_metric_name: false
  allow_structured_metadata: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_query_series: 300000
  max_chunks_per_query: 3000000
  max_query_parallelism: 64
  max_cache_freshness_per_query: '30m'
  split_queries_by_interval: 8h
  retention_period: 365d

#compactor:
#  delete_request_cancel_period: 10m
#  retention_enabled: true
#  retention_delete_delay: 20m

table_manager:
  retention_deletes_enabled: true
  retention_period: 365d

#chunk_store_config:
#  max_look_back_period: 0 

analytics:
  reporting_enabled: false
